# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish  Package

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v2
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name "Animesh Jain"
      - run: git config --global user.email "animesh.jain1203@gmail.com"
      - run: npm ci
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
