# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# Fo more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test Coverage

on:
  pull_request:
    branches: [master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 21
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
